name: Build and Test

on: push

jobs:
  build-with-cabal:
    name: ${{ matrix.os }} / ghc-${{ matrix.ghc }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - macOS-10.15
          - macOS-11
          - macOS-12
          - windows-2019
          - windows-2022
        ghc:
          - 8.2.2
          - 8.4.4
          - 8.6.5
          - 8.8.2
          - 8.10.7
          - 9.0.2
          - 9.2.4
          - 9.4.2
        cabal:
          - latest
        exclude:
          # can't build basement (indirect dependency)
          - os: ubuntu-18.04
            ghc: 8.4.4
          # ghc-8.2.2 fails to install
          - os: ubuntu-22.04
            ghc: 8.2.2
    env:
      runtests: ${{ matrix.ghc == '8.2.2' || matrix.ghc == '9.4.2' }}
      # for some reason this test randomly fails with darcs.net server
      # timeouts similar errors
      tests-to-run: -t='!network/log'
      testcmd: cabal run -- darcs-test -j=6 -f=123 -i=yn -c=yn --hide
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # avoid occasional timeouts in test scripts that access darcs.net:
      DARCS_CONNECTION_TIMEOUT: 15

    steps:
    - name: Configure git
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf input

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Haskell
      id: setup-haskell-cabal
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache cabal store
      uses: actions/cache@v3
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: cabal-store-${{ matrix.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('darcs.cabal', 'cabal.project') }}
        restore-keys: |
          cabal-store-${{ matrix.os }}-ghc-${{ matrix.ghc }}-

    - name: Configure
      run: cabal configure --enable-tests -fwarn-as-error

    - name: Build dependencies
      run: cabal build --only-dependencies

    - name: Cache dist-newstyle
      uses: actions/cache@v3
      with:
        path: dist-newstyle/build
        key: dist-newstyle-${{ matrix.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('dist-newstyle/cache/plan.json','Setup.hs','*.cabal','cabal*','darcs/*','src/**','harness/**','shelly/src/**','release/*') }}
        restore-keys: |
          dist-newstyle-${{ matrix.os }}-ghc-${{ matrix.ghc }}

    - name: Build
      run: cabal build

    - name: Haddock
      if: matrix.ghc != '8.2.2' && matrix.ghc != '8.4.4'
      run: cabal haddock lib:darcs

    - name: Run tests on Linux
      if: runner.os == 'Linux' && env.runtests == 'true'
      run: |
        sudo apt-get install lighttpd
        ${{ env.testcmd }} ${{ env.tests-to-run }}

    - name: Run tests on MacOS
      if: runner.os == 'macOS' && env.runtests == 'true'
      run: |
        brew install lighttpd
        brew install gnu-sed
        PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
        ${{ env.testcmd }} ${{ env.tests-to-run }}

    - name: Run tests on Windows
      if: runner.os == 'Windows' && env.runtests == 'true'
      # running the tests for all three patch formats takes over an hour
      run: cabal run -- darcs-test -j=6 -f=2 -s=sn -i=yn ${{ env.tests-to-run }} --hide
